/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as LupaPasswordRouteImport } from './routes/lupa-password'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as HargaRouteImport } from './routes/harga'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTransactionsIndexRouteImport } from './routes/admin/transactions/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminCoursesNewRouteImport } from './routes/admin/courses/new'
import { Route as AuthedDashboardProfilRouteImport } from './routes/_authed/dashboard_.profil'
import { Route as AuthedDashboardKursusRouteImport } from './routes/_authed/dashboard_.kursus'
import { Route as AuthedDashboardKontakRouteImport } from './routes/_authed/dashboard_.kontak'
import { Route as AuthedDashboardBantuanRouteImport } from './routes/_authed/dashboard_.bantuan'
import { Route as AdminCoursesSlugIndexRouteImport } from './routes/admin/courses/$slug.index'
import { Route as AdminCoursesSlugEditRouteImport } from './routes/admin/courses/$slug.edit'
import { Route as AuthedCoursesSlugLearnRouteImport } from './routes/_authed/courses.$slug.learn'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaPasswordRoute = LupaPasswordRouteImport.update({
  id: '/lupa-password',
  path: '/lupa-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const HargaRoute = HargaRouteImport.update({
  id: '/harga',
  path: '/harga',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsIndexRoute = AdminTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedDashboardProfilRoute = AuthedDashboardProfilRouteImport.update({
  id: '/dashboard_/profil',
  path: '/dashboard/profil',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardKursusRoute = AuthedDashboardKursusRouteImport.update({
  id: '/dashboard_/kursus',
  path: '/dashboard/kursus',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardKontakRoute = AuthedDashboardKontakRouteImport.update({
  id: '/dashboard_/kontak',
  path: '/dashboard/kontak',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardBantuanRoute = AuthedDashboardBantuanRouteImport.update({
  id: '/dashboard_/bantuan',
  path: '/dashboard/bantuan',
  getParentRoute: () => AuthedRoute,
} as any)
const AdminCoursesSlugIndexRoute = AdminCoursesSlugIndexRouteImport.update({
  id: '/courses/$slug/',
  path: '/courses/$slug/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesSlugEditRoute = AdminCoursesSlugEditRouteImport.update({
  id: '/courses/$slug/edit',
  path: '/courses/$slug/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedCoursesSlugLearnRoute = AuthedCoursesSlugLearnRouteImport.update({
  id: '/courses/$slug/learn',
  path: '/courses/$slug/learn',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/daftar': typeof DaftarRoute
  '/harga': typeof HargaRoute
  '/logout': typeof LogoutRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/masuk': typeof MasukRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard/bantuan': typeof AuthedDashboardBantuanRoute
  '/dashboard/kontak': typeof AuthedDashboardKontakRoute
  '/dashboard/kursus': typeof AuthedDashboardKursusRoute
  '/dashboard/profil': typeof AuthedDashboardProfilRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/transactions': typeof AdminTransactionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/courses/$slug/learn': typeof AuthedCoursesSlugLearnRoute
  '/admin/courses/$slug/edit': typeof AdminCoursesSlugEditRoute
  '/admin/courses/$slug': typeof AdminCoursesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/harga': typeof HargaRoute
  '/logout': typeof LogoutRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/masuk': typeof MasukRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard/bantuan': typeof AuthedDashboardBantuanRoute
  '/dashboard/kontak': typeof AuthedDashboardKontakRoute
  '/dashboard/kursus': typeof AuthedDashboardKursusRoute
  '/dashboard/profil': typeof AuthedDashboardProfilRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/transactions': typeof AdminTransactionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/courses/$slug/learn': typeof AuthedCoursesSlugLearnRoute
  '/admin/courses/$slug/edit': typeof AdminCoursesSlugEditRoute
  '/admin/courses/$slug': typeof AdminCoursesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/daftar': typeof DaftarRoute
  '/harga': typeof HargaRoute
  '/logout': typeof LogoutRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/masuk': typeof MasukRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authed/dashboard_/bantuan': typeof AuthedDashboardBantuanRoute
  '/_authed/dashboard_/kontak': typeof AuthedDashboardKontakRoute
  '/_authed/dashboard_/kursus': typeof AuthedDashboardKursusRoute
  '/_authed/dashboard_/profil': typeof AuthedDashboardProfilRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_authed/courses/$slug/learn': typeof AuthedCoursesSlugLearnRoute
  '/admin/courses/$slug/edit': typeof AdminCoursesSlugEditRoute
  '/admin/courses/$slug/': typeof AdminCoursesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/daftar'
    | '/harga'
    | '/logout'
    | '/lupa-password'
    | '/masuk'
    | '/reset-password'
    | '/tentang'
    | '/dashboard'
    | '/auth/callback'
    | '/courses/$slug'
    | '/admin/'
    | '/courses'
    | '/dashboard/bantuan'
    | '/dashboard/kontak'
    | '/dashboard/kursus'
    | '/dashboard/profil'
    | '/admin/courses/new'
    | '/admin/courses'
    | '/admin/transactions'
    | '/admin/users'
    | '/courses/$slug/learn'
    | '/admin/courses/$slug/edit'
    | '/admin/courses/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/harga'
    | '/logout'
    | '/lupa-password'
    | '/masuk'
    | '/reset-password'
    | '/tentang'
    | '/dashboard'
    | '/auth/callback'
    | '/courses/$slug'
    | '/admin'
    | '/courses'
    | '/dashboard/bantuan'
    | '/dashboard/kontak'
    | '/dashboard/kursus'
    | '/dashboard/profil'
    | '/admin/courses/new'
    | '/admin/courses'
    | '/admin/transactions'
    | '/admin/users'
    | '/courses/$slug/learn'
    | '/admin/courses/$slug/edit'
    | '/admin/courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/admin'
    | '/daftar'
    | '/harga'
    | '/logout'
    | '/lupa-password'
    | '/masuk'
    | '/reset-password'
    | '/tentang'
    | '/_authed/dashboard'
    | '/auth/callback'
    | '/courses/$slug'
    | '/admin/'
    | '/courses/'
    | '/_authed/dashboard_/bantuan'
    | '/_authed/dashboard_/kontak'
    | '/_authed/dashboard_/kursus'
    | '/_authed/dashboard_/profil'
    | '/admin/courses/new'
    | '/admin/courses/'
    | '/admin/transactions/'
    | '/admin/users/'
    | '/_authed/courses/$slug/learn'
    | '/admin/courses/$slug/edit'
    | '/admin/courses/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DaftarRoute: typeof DaftarRoute
  HargaRoute: typeof HargaRoute
  LogoutRoute: typeof LogoutRoute
  LupaPasswordRoute: typeof LupaPasswordRoute
  MasukRoute: typeof MasukRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TentangRoute: typeof TentangRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-password': {
      id: '/lupa-password'
      path: '/lupa-password'
      fullPath: '/lupa-password'
      preLoaderRoute: typeof LupaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harga': {
      id: '/harga'
      path: '/harga'
      fullPath: '/harga'
      preLoaderRoute: typeof HargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions/': {
      id: '/admin/transactions/'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/dashboard_/profil': {
      id: '/_authed/dashboard_/profil'
      path: '/dashboard/profil'
      fullPath: '/dashboard/profil'
      preLoaderRoute: typeof AuthedDashboardProfilRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard_/kursus': {
      id: '/_authed/dashboard_/kursus'
      path: '/dashboard/kursus'
      fullPath: '/dashboard/kursus'
      preLoaderRoute: typeof AuthedDashboardKursusRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard_/kontak': {
      id: '/_authed/dashboard_/kontak'
      path: '/dashboard/kontak'
      fullPath: '/dashboard/kontak'
      preLoaderRoute: typeof AuthedDashboardKontakRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard_/bantuan': {
      id: '/_authed/dashboard_/bantuan'
      path: '/dashboard/bantuan'
      fullPath: '/dashboard/bantuan'
      preLoaderRoute: typeof AuthedDashboardBantuanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/admin/courses/$slug/': {
      id: '/admin/courses/$slug/'
      path: '/courses/$slug'
      fullPath: '/admin/courses/$slug'
      preLoaderRoute: typeof AdminCoursesSlugIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$slug/edit': {
      id: '/admin/courses/$slug/edit'
      path: '/courses/$slug/edit'
      fullPath: '/admin/courses/$slug/edit'
      preLoaderRoute: typeof AdminCoursesSlugEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/courses/$slug/learn': {
      id: '/_authed/courses/$slug/learn'
      path: '/courses/$slug/learn'
      fullPath: '/courses/$slug/learn'
      preLoaderRoute: typeof AuthedCoursesSlugLearnRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDashboardBantuanRoute: typeof AuthedDashboardBantuanRoute
  AuthedDashboardKontakRoute: typeof AuthedDashboardKontakRoute
  AuthedDashboardKursusRoute: typeof AuthedDashboardKursusRoute
  AuthedDashboardProfilRoute: typeof AuthedDashboardProfilRoute
  AuthedCoursesSlugLearnRoute: typeof AuthedCoursesSlugLearnRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDashboardBantuanRoute: AuthedDashboardBantuanRoute,
  AuthedDashboardKontakRoute: AuthedDashboardKontakRoute,
  AuthedDashboardKursusRoute: AuthedDashboardKursusRoute,
  AuthedDashboardProfilRoute: AuthedDashboardProfilRoute,
  AuthedCoursesSlugLearnRoute: AuthedCoursesSlugLearnRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminTransactionsIndexRoute: typeof AdminTransactionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminCoursesSlugEditRoute: typeof AdminCoursesSlugEditRoute
  AdminCoursesSlugIndexRoute: typeof AdminCoursesSlugIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminTransactionsIndexRoute: AdminTransactionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminCoursesSlugEditRoute: AdminCoursesSlugEditRoute,
  AdminCoursesSlugIndexRoute: AdminCoursesSlugIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DaftarRoute: DaftarRoute,
  HargaRoute: HargaRoute,
  LogoutRoute: LogoutRoute,
  LupaPasswordRoute: LupaPasswordRoute,
  MasukRoute: MasukRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TentangRoute: TentangRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
