/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as LupaPasswordRouteImport } from './routes/lupa-password'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as HargaRouteImport } from './routes/harga'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCoursesSlugLearnRouteImport } from './routes/_authed/courses.$slug.learn'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaPasswordRoute = LupaPasswordRouteImport.update({
  id: '/lupa-password',
  path: '/lupa-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const HargaRoute = HargaRouteImport.update({
  id: '/harga',
  path: '/harga',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCoursesSlugLearnRoute = AuthedCoursesSlugLearnRouteImport.update({
  id: '/courses/$slug/learn',
  path: '/courses/$slug/learn',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/harga': typeof HargaRoute
  '/logout': typeof LogoutRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/masuk': typeof MasukRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/courses/$slug/learn': typeof AuthedCoursesSlugLearnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/harga': typeof HargaRoute
  '/logout': typeof LogoutRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/masuk': typeof MasukRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/courses/$slug/learn': typeof AuthedCoursesSlugLearnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/daftar': typeof DaftarRoute
  '/harga': typeof HargaRoute
  '/logout': typeof LogoutRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/masuk': typeof MasukRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authed/courses/$slug/learn': typeof AuthedCoursesSlugLearnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftar'
    | '/harga'
    | '/logout'
    | '/lupa-password'
    | '/masuk'
    | '/reset-password'
    | '/tentang'
    | '/dashboard'
    | '/auth/callback'
    | '/courses/$slug'
    | '/courses'
    | '/courses/$slug/learn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/harga'
    | '/logout'
    | '/lupa-password'
    | '/masuk'
    | '/reset-password'
    | '/tentang'
    | '/dashboard'
    | '/auth/callback'
    | '/courses/$slug'
    | '/courses'
    | '/courses/$slug/learn'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/daftar'
    | '/harga'
    | '/logout'
    | '/lupa-password'
    | '/masuk'
    | '/reset-password'
    | '/tentang'
    | '/_authed/dashboard'
    | '/auth/callback'
    | '/courses/$slug'
    | '/courses/'
    | '/_authed/courses/$slug/learn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DaftarRoute: typeof DaftarRoute
  HargaRoute: typeof HargaRoute
  LogoutRoute: typeof LogoutRoute
  LupaPasswordRoute: typeof LupaPasswordRoute
  MasukRoute: typeof MasukRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TentangRoute: typeof TentangRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-password': {
      id: '/lupa-password'
      path: '/lupa-password'
      fullPath: '/lupa-password'
      preLoaderRoute: typeof LupaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harga': {
      id: '/harga'
      path: '/harga'
      fullPath: '/harga'
      preLoaderRoute: typeof HargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/courses/$slug/learn': {
      id: '/_authed/courses/$slug/learn'
      path: '/courses/$slug/learn'
      fullPath: '/courses/$slug/learn'
      preLoaderRoute: typeof AuthedCoursesSlugLearnRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedCoursesSlugLearnRoute: typeof AuthedCoursesSlugLearnRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedCoursesSlugLearnRoute: AuthedCoursesSlugLearnRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DaftarRoute: DaftarRoute,
  HargaRoute: HargaRoute,
  LogoutRoute: LogoutRoute,
  LupaPasswordRoute: LupaPasswordRoute,
  MasukRoute: MasukRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TentangRoute: TentangRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
